spring:
  application:
    name: session-csrf-demo

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.csrf: TRACE
    org.springframework.security.web.session: TRACE
    com.example: DEBUG

server:
  port: 8080
  servlet:
    session:
      timeout: 30m
      cookie:
        name: SESSIONID
        http-only: true
        secure: false
        same-site: strict